### ISSUE TITLE
[Suggestion] Compatibilty for Auga UI mod

### ISSUE THREAD

**Issue by cCaptainn** [thedefside/BetterUI#10]
https://github.com/RandyKnapp/Auga

I'd love to use both of your mods together and toggle what I like to keep. Auga has an API, so it's not impossible to make them compatible. Would you consider this, mighty dev?

**Comment by thedefside** [comment]
This would not be possible. A completely new mod would have to be created basically to add support for Auga. If there are features from BetterUi that you would like to see in Auga, you should propose them to Randy.
