### ISSUE TITLE
Unable to edit elements

### ISSUE THREAD

**Issue by Jokinen86** [thedefside/BetterUI#12]
With the most recent game update (0.207.20), I'm unable to edit UI elements. The HUD editing interface appears normally but nothing can be moved or resized.

**Comment by Devestatio** [comment]
This is the error being spammed when you try to edit the UI, in case it helps.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BetterUI.GameClasses.BetterHud.Update (Hud __instance) (at <f355970278c44af48fff0d2b8b0bc00d>:0)
(wrapper dynamic-method) Hud.DMD<Hud::Update>(Hud)

**Comment by ReaperAlpha** [comment]
Verified to be happening on 2 of my machines as well. 

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BetterUI.GameClasses.BetterHud.Update (Hud __instance) (at <f355970278c44af48fff0d2b8b0bc00d>:0)
(wrapper dynamic-method) Hud.DMD<Hud::Update>(Hud)

**Comment by thedefside** [comment]
Resolved in #17
