### ISSUE TITLE
The new official update 212 broken this mod

### ISSUE THREAD

**Issue by Nesishoot** [thedefside/BetterUI#24]
Hello,

My game updated to receive Mistland and the mod no longer works at all, I think you already know, it needs to be updated, thanks :)

**Comment by thedefside** [comment]
When you open an issue you need to provide a detailed description of the problem including error messages, screenshots, and any other relevant info like what version of the game you are using and what mods and what versions of those you are using.

**Comment by Nesishoot** [comment]
Ok thank you :D
