### ISSUE TITLE
stamina/health/food bars gone in 2.3.0

### ISSUE THREAD

**Issue by Richelieu77** [thedefside/BetterUI#36]
What the title says.  They also don't appear in HUD edit mode.  I rolled back to 2.2.3, and it works again.  I made no changes in my config file.

**Comment by thedefside** [comment]
They were moved to a different section in the config

**Comment by Goldenrevolver** [comment]
sorry, there was a small miscommunication with the pull request. the backwards compatibility for the config didn't quite make it into the release. we are working on it
