### ISSUE TITLE
Compatibility issue with 'Equip Multiple Utility Items'

### ISSUE THREAD

**Issue by DaveKX** [thedefside/BetterUI#43]
Hello, seems like when I have both mods loaded and I join a world, all my equipped armor and whatever I have in the quick slots, all items are lost... I don't know if this issue is in your end, or in aedenthorn's end, but it makes both mods unusable together. Just in case it's on their end I posted on their nexus mod page as well.

**Comment by thedefside** [comment]
@DaveKX can you try this pre-release version and let me know if it still happens?

https://github.com/thedefside/BetterUI/releases/download/v2.4.0_pre-release/BetterUI.dll

**Comment by DaveKX** [comment]
It still happens, the trigger seems to be having more than 1 utility item equipped. Upon joining the world when you have more than 1 utility item equipped, all items that are in EAQS slots are deleted, and the utility that was in the EAQS slot is deleted as well, obviously, and is replace by another that you had equipped but was before in the inventory slots.

**Comment by thedefside** [comment]
Are you getting any errors in you log?

**Comment by DaveKX** [comment]
No errors, but seems like after all it's a problem with only EAQS and not with Better UI + EAQS. But still weird that I get no errors at all. And well, if it's a problem with EAQS I guess it's a lost cause then xD, I'll see what I can get in their discord, thx for the help! (and sorry for mistaking the mod that was causing the problem)
