### ISSUE TITLE
Havlov Kills no show

### ISSUE THREAD

**Issue by myceliated** [thedefside/BetterUI#55]
![image](https://user-images.githubusercontent.com/37879648/215007228-1aa3e24e-c87e-43c3-b1ad-af494eddc187.png)
Havlov has killed many! ..but count remains 0 while deaths, crafts, and builds rise. Help Havlov?

**Comment by thedefside** [comment]
Havlov use old version. BetterUI fix long time ago.

**Comment by myceliated** [comment]
Havlov uses BetterUI v2.4.1

Where is newer version?

**Comment by thedefside** [comment]
Send me your logoutput.log file

**Comment by myceliated** [comment]
[LogOutput.log](https://github.com/thedefside/BetterUI/files/10521654/LogOutput.log)

**Comment by thedefside** [comment]
AwleStats:
![image](https://user-images.githubusercontent.com/32403915/215160997-0f0df485-d93f-4bf2-b526-ec1c70656df9.png)

BetterUI:
![image](https://user-images.githubusercontent.com/32403915/215161091-35db6d9d-6bf3-46e2-a9f2-20a7dce6a5f4.png)

**Comment by myceliated** [comment]
Oh okay I was thinking that may be the conflict.

was just wodnering because in the betterui config the [ showCustomCharInfo = true ] description says, "Also shows the Kills stat if something increases it (the base game doesn't)."

Do you know what raises the stat, or do have Kills disabled for now? Is that 'kills' stat completely from awlestats thingy you reckon?

**Comment by thedefside** [comment]
The value is taken from your character file. It is always 0 and nothing raises it. So, to stop people from asking about it, we've hidden it if it is 0. If it's not 0, it will be displayed.

It appears the AwleStats is getting the last word here when you have both installed.

**Comment by myceliated** [comment]
Understandable. Thank you very much for your BetterUI.
