### ISSUE TITLE
Publish to nexus mods

### ISSUE THREAD

**Issue by cdobbyn** [thedefside/BetterUI#58]
Please consider publishing this to nexus mods.

**Comment by Goldenrevolver** [comment]
that would be against the permission settings of the original BetterUI mod on nexus https://www.nexusmods.com/valheim/mods/189

while the source code is licences under "BSD 2-Clause "Simplified" License", the permission settings on nexus kind of contradict that. and the original author of BetterUI is sadly no longer around
