### ISSUE TITLE
'EnemyHud/HudData.m_name' not found. error

### ISSUE THREAD

**Issue by GloryLynn** [thedefside/BetterUI#60]
Following update on Steam, i now get the following...  The name plates are stuck at the initial loading point and do not update or move as the mob or character moves.

[Error  : Unity Log] MissingFieldException: Field 'EnemyHud/HudData.m_name' not found.
Stack trace:
(wrapper dynamic-method) EnemyHud.DMD<EnemyHud::ShowHud>(EnemyHud,Character,bool)
(wrapper dynamic-method) EnemyHud.DMD<EnemyHud::LateUpdate>(EnemyHud)

**Comment by Babkatt** [comment]
Got the same issue. Tried disabling bunch of stuff in the config but nothing turned if off. Uploaded screenshot.
![20230313113821_1](https://user-images.githubusercontent.com/127775044/224798555-a97e30d1-108c-4f78-a8fb-45ea299d8213.jpg)

**Comment by Talesz** [comment]
![vug](https://user-images.githubusercontent.com/17534109/224823780-222a24fa-e492-4135-8ae1-cf614a55b9d0.png)

**Comment by olavr-dev** [comment]
As a workaround until BetterUI gets updated you can use Enhuddlement by ComfyMods. It patches out the EnemyHUD changes of BetterUI and is updated for 0.214.2.

**Comment by Nomado-Coyote** [comment]
> 

does one need to disable BetterUI for now though or does it like work on top of it and fixes for now?

**Comment by Nomado-Coyote** [comment]
> As a workaround until BetterUI gets updated you can use Enhuddlement by ComfyMods. It patches out the EnemyHUD changes of BetterUI and is updated for 0.214.2.

does one need to disable BetterUI for now though or does it like work on top of it and fixes for now?

**Comment by GloryLynn** [comment]
If you use Enhuddlement it does everything for you, i tried it out earlier and i get all the features of BetterUI and none of the errors in the command prompt or associated lag from it.
