### ISSUE TITLE
[request] Enemy HP bar and tamed creature HP bar adjustments

### ISSUE THREAD

**Issue by pjmichor** [thedefside/BetterUI#9]
Is it possible to request that we can have tamed creature health bars appear green without needing to enable the enemy health bar changes?

Additionally, is it possible to add option(s) to set the thickness of HP bars, both allied and enemy?

Thanks!

**Comment by thedefside** [comment]
how about this: if the HP text is turned off, the bar goes back to it's original height.

**Comment by pjmichor** [comment]
Ooooh that's a good idea! Then you can either have bar with text, or bar without text.

**Comment by thedefside** [comment]
Resolved in #17

**Comment by pjmichor** [comment]
blessed dev, nice work!
